#!/bin/bash

wifistatus="$(cat /sys/class/net/w*/operstate)"
ethstatus="$(cat /sys/class/net/e*/operstate)"
if [ $wifistatus = "up" ]; then 
    essid="$(nmcli c | sed -n '2{p;q}' | awk '{print $1}')"
    quality="$(cat /proc/net/wireless |  sed -n '3{p;q}' | awk '{printf "%.0f\n",$3}')"
elif [ $ethstatus = "up" ]; then
    essid="$(nmcli c | sed -n '2{p;q}' | awk '{print $5}')"
    quality=""
elif [ -d /sys/class/net/enp0s20f0u* ]; then
    essid="$(nmcli c | sed -n '2{p;q}' | awk '{print $5}')"
    quality=""
else
    essid="Disconnected"
    quality=""
fi
printf "%s %s" "$essid" "$quality"

	
